// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// TasColumns holds the columns for the "tas" table.
	TasColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "evidence", Type: field.TypeString},
		{Name: "repository", Type: field.TypeString},
		{Name: "commit_id", Type: field.TypeString},
		{Name: "public_key", Type: field.TypeBytes},
	}
	// TasTable holds the schema information for the "tas" table.
	TasTable = &schema.Table{
		Name:       "tas",
		Columns:    TasColumns,
		PrimaryKey: []*schema.Column{TasColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		TasTable,
	}
)

func init() {
}
