// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// CTLog is the predicate function for ctlog builders.
type CTLog func(*sql.Selector)

// EvidenceLog is the predicate function for evidencelog builders.
type EvidenceLog func(*sql.Selector)

// Subscription is the predicate function for subscription builders.
type Subscription func(*sql.Selector)

// TA is the predicate function for ta builders.
type TA func(*sql.Selector)
