// Code generated by ent, DO NOT EDIT.

package subscription

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the subscription type in the database.
	Label = "subscription"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEndpoint holds the string denoting the endpoint field in the database.
	FieldEndpoint = "endpoint"
	// FieldP256dh holds the string denoting the p256dh field in the database.
	FieldP256dh = "p256dh"
	// FieldAuth holds the string denoting the auth field in the database.
	FieldAuth = "auth"
	// Table holds the table name of the subscription in the database.
	Table = "subscriptions"
)

// Columns holds all SQL columns for subscription fields.
var Columns = []string{
	FieldID,
	FieldEndpoint,
	FieldP256dh,
	FieldAuth,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Subscription queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByEndpoint orders the results by the endpoint field.
func ByEndpoint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndpoint, opts...).ToFunc()
}

// ByP256dh orders the results by the p256dh field.
func ByP256dh(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldP256dh, opts...).ToFunc()
}

// ByAuth orders the results by the auth field.
func ByAuth(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuth, opts...).ToFunc()
}
