// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/anonymous-author-00000/ra-webs/monitor/ent/evidencelog"
	"github.com/anonymous-author-00000/ra-webs/monitor/ent/predicate"
	"github.com/anonymous-author-00000/ra-webs/monitor/ent/ta"
)

// EvidenceLogQuery is the builder for querying EvidenceLog entities.
type EvidenceLogQuery struct {
	config
	ctx        *QueryContext
	order      []evidencelog.OrderOption
	inters     []Interceptor
	predicates []predicate.EvidenceLog
	withTa     *TAQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the EvidenceLogQuery builder.
func (elq *EvidenceLogQuery) Where(ps ...predicate.EvidenceLog) *EvidenceLogQuery {
	elq.predicates = append(elq.predicates, ps...)
	return elq
}

// Limit the number of records to be returned by this query.
func (elq *EvidenceLogQuery) Limit(limit int) *EvidenceLogQuery {
	elq.ctx.Limit = &limit
	return elq
}

// Offset to start from.
func (elq *EvidenceLogQuery) Offset(offset int) *EvidenceLogQuery {
	elq.ctx.Offset = &offset
	return elq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (elq *EvidenceLogQuery) Unique(unique bool) *EvidenceLogQuery {
	elq.ctx.Unique = &unique
	return elq
}

// Order specifies how the records should be ordered.
func (elq *EvidenceLogQuery) Order(o ...evidencelog.OrderOption) *EvidenceLogQuery {
	elq.order = append(elq.order, o...)
	return elq
}

// QueryTa chains the current query on the "ta" edge.
func (elq *EvidenceLogQuery) QueryTa() *TAQuery {
	query := (&TAClient{config: elq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := elq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := elq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(evidencelog.Table, evidencelog.FieldID, selector),
			sqlgraph.To(ta.Table, ta.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, evidencelog.TaTable, evidencelog.TaColumn),
		)
		fromU = sqlgraph.SetNeighbors(elq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first EvidenceLog entity from the query.
// Returns a *NotFoundError when no EvidenceLog was found.
func (elq *EvidenceLogQuery) First(ctx context.Context) (*EvidenceLog, error) {
	nodes, err := elq.Limit(1).All(setContextOp(ctx, elq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{evidencelog.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (elq *EvidenceLogQuery) FirstX(ctx context.Context) *EvidenceLog {
	node, err := elq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first EvidenceLog ID from the query.
// Returns a *NotFoundError when no EvidenceLog ID was found.
func (elq *EvidenceLogQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = elq.Limit(1).IDs(setContextOp(ctx, elq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{evidencelog.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (elq *EvidenceLogQuery) FirstIDX(ctx context.Context) int {
	id, err := elq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single EvidenceLog entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one EvidenceLog entity is found.
// Returns a *NotFoundError when no EvidenceLog entities are found.
func (elq *EvidenceLogQuery) Only(ctx context.Context) (*EvidenceLog, error) {
	nodes, err := elq.Limit(2).All(setContextOp(ctx, elq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{evidencelog.Label}
	default:
		return nil, &NotSingularError{evidencelog.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (elq *EvidenceLogQuery) OnlyX(ctx context.Context) *EvidenceLog {
	node, err := elq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only EvidenceLog ID in the query.
// Returns a *NotSingularError when more than one EvidenceLog ID is found.
// Returns a *NotFoundError when no entities are found.
func (elq *EvidenceLogQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = elq.Limit(2).IDs(setContextOp(ctx, elq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{evidencelog.Label}
	default:
		err = &NotSingularError{evidencelog.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (elq *EvidenceLogQuery) OnlyIDX(ctx context.Context) int {
	id, err := elq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of EvidenceLogs.
func (elq *EvidenceLogQuery) All(ctx context.Context) ([]*EvidenceLog, error) {
	ctx = setContextOp(ctx, elq.ctx, ent.OpQueryAll)
	if err := elq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*EvidenceLog, *EvidenceLogQuery]()
	return withInterceptors[[]*EvidenceLog](ctx, elq, qr, elq.inters)
}

// AllX is like All, but panics if an error occurs.
func (elq *EvidenceLogQuery) AllX(ctx context.Context) []*EvidenceLog {
	nodes, err := elq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of EvidenceLog IDs.
func (elq *EvidenceLogQuery) IDs(ctx context.Context) (ids []int, err error) {
	if elq.ctx.Unique == nil && elq.path != nil {
		elq.Unique(true)
	}
	ctx = setContextOp(ctx, elq.ctx, ent.OpQueryIDs)
	if err = elq.Select(evidencelog.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (elq *EvidenceLogQuery) IDsX(ctx context.Context) []int {
	ids, err := elq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (elq *EvidenceLogQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, elq.ctx, ent.OpQueryCount)
	if err := elq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, elq, querierCount[*EvidenceLogQuery](), elq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (elq *EvidenceLogQuery) CountX(ctx context.Context) int {
	count, err := elq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (elq *EvidenceLogQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, elq.ctx, ent.OpQueryExist)
	switch _, err := elq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (elq *EvidenceLogQuery) ExistX(ctx context.Context) bool {
	exist, err := elq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the EvidenceLogQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (elq *EvidenceLogQuery) Clone() *EvidenceLogQuery {
	if elq == nil {
		return nil
	}
	return &EvidenceLogQuery{
		config:     elq.config,
		ctx:        elq.ctx.Clone(),
		order:      append([]evidencelog.OrderOption{}, elq.order...),
		inters:     append([]Interceptor{}, elq.inters...),
		predicates: append([]predicate.EvidenceLog{}, elq.predicates...),
		withTa:     elq.withTa.Clone(),
		// clone intermediate query.
		sql:  elq.sql.Clone(),
		path: elq.path,
	}
}

// WithTa tells the query-builder to eager-load the nodes that are connected to
// the "ta" edge. The optional arguments are used to configure the query builder of the edge.
func (elq *EvidenceLogQuery) WithTa(opts ...func(*TAQuery)) *EvidenceLogQuery {
	query := (&TAClient{config: elq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	elq.withTa = query
	return elq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Evidence string `json:"evidence,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.EvidenceLog.Query().
//		GroupBy(evidencelog.FieldEvidence).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (elq *EvidenceLogQuery) GroupBy(field string, fields ...string) *EvidenceLogGroupBy {
	elq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &EvidenceLogGroupBy{build: elq}
	grbuild.flds = &elq.ctx.Fields
	grbuild.label = evidencelog.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Evidence string `json:"evidence,omitempty"`
//	}
//
//	client.EvidenceLog.Query().
//		Select(evidencelog.FieldEvidence).
//		Scan(ctx, &v)
func (elq *EvidenceLogQuery) Select(fields ...string) *EvidenceLogSelect {
	elq.ctx.Fields = append(elq.ctx.Fields, fields...)
	sbuild := &EvidenceLogSelect{EvidenceLogQuery: elq}
	sbuild.label = evidencelog.Label
	sbuild.flds, sbuild.scan = &elq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a EvidenceLogSelect configured with the given aggregations.
func (elq *EvidenceLogQuery) Aggregate(fns ...AggregateFunc) *EvidenceLogSelect {
	return elq.Select().Aggregate(fns...)
}

func (elq *EvidenceLogQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range elq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, elq); err != nil {
				return err
			}
		}
	}
	for _, f := range elq.ctx.Fields {
		if !evidencelog.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if elq.path != nil {
		prev, err := elq.path(ctx)
		if err != nil {
			return err
		}
		elq.sql = prev
	}
	return nil
}

func (elq *EvidenceLogQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*EvidenceLog, error) {
	var (
		nodes       = []*EvidenceLog{}
		_spec       = elq.querySpec()
		loadedTypes = [1]bool{
			elq.withTa != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*EvidenceLog).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &EvidenceLog{config: elq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, elq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := elq.withTa; query != nil {
		if err := elq.loadTa(ctx, query, nodes, nil,
			func(n *EvidenceLog, e *TA) { n.Edges.Ta = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (elq *EvidenceLogQuery) loadTa(ctx context.Context, query *TAQuery, nodes []*EvidenceLog, init func(*EvidenceLog), assign func(*EvidenceLog, *TA)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*EvidenceLog)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
	}
	query.withFKs = true
	query.Where(predicate.TA(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(evidencelog.TaColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.evidence_log_ta
		if fk == nil {
			return fmt.Errorf(`foreign-key "evidence_log_ta" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "evidence_log_ta" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (elq *EvidenceLogQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := elq.querySpec()
	_spec.Node.Columns = elq.ctx.Fields
	if len(elq.ctx.Fields) > 0 {
		_spec.Unique = elq.ctx.Unique != nil && *elq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, elq.driver, _spec)
}

func (elq *EvidenceLogQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(evidencelog.Table, evidencelog.Columns, sqlgraph.NewFieldSpec(evidencelog.FieldID, field.TypeInt))
	_spec.From = elq.sql
	if unique := elq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if elq.path != nil {
		_spec.Unique = true
	}
	if fields := elq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, evidencelog.FieldID)
		for i := range fields {
			if fields[i] != evidencelog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := elq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := elq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := elq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := elq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (elq *EvidenceLogQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(elq.driver.Dialect())
	t1 := builder.Table(evidencelog.Table)
	columns := elq.ctx.Fields
	if len(columns) == 0 {
		columns = evidencelog.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if elq.sql != nil {
		selector = elq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if elq.ctx.Unique != nil && *elq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range elq.predicates {
		p(selector)
	}
	for _, p := range elq.order {
		p(selector)
	}
	if offset := elq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := elq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// EvidenceLogGroupBy is the group-by builder for EvidenceLog entities.
type EvidenceLogGroupBy struct {
	selector
	build *EvidenceLogQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (elgb *EvidenceLogGroupBy) Aggregate(fns ...AggregateFunc) *EvidenceLogGroupBy {
	elgb.fns = append(elgb.fns, fns...)
	return elgb
}

// Scan applies the selector query and scans the result into the given value.
func (elgb *EvidenceLogGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, elgb.build.ctx, ent.OpQueryGroupBy)
	if err := elgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EvidenceLogQuery, *EvidenceLogGroupBy](ctx, elgb.build, elgb, elgb.build.inters, v)
}

func (elgb *EvidenceLogGroupBy) sqlScan(ctx context.Context, root *EvidenceLogQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(elgb.fns))
	for _, fn := range elgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*elgb.flds)+len(elgb.fns))
		for _, f := range *elgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*elgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := elgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// EvidenceLogSelect is the builder for selecting fields of EvidenceLog entities.
type EvidenceLogSelect struct {
	*EvidenceLogQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (els *EvidenceLogSelect) Aggregate(fns ...AggregateFunc) *EvidenceLogSelect {
	els.fns = append(els.fns, fns...)
	return els
}

// Scan applies the selector query and scans the result into the given value.
func (els *EvidenceLogSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, els.ctx, ent.OpQuerySelect)
	if err := els.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EvidenceLogQuery, *EvidenceLogSelect](ctx, els.EvidenceLogQuery, els, els.inters, v)
}

func (els *EvidenceLogSelect) sqlScan(ctx context.Context, root *EvidenceLogQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(els.fns))
	for _, fn := range els.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*els.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := els.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
