// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/anonymous-author-00000/ra-webs/monitor/ent/schema"
	"github.com/anonymous-author-00000/ra-webs/monitor/ent/ta"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	taFields := schema.TA{}.Fields()
	_ = taFields
	// taDescIsActive is the schema descriptor for is_active field.
	taDescIsActive := taFields[1].Descriptor()
	// ta.DefaultIsActive holds the default value on creation for the is_active field.
	ta.DefaultIsActive = taDescIsActive.Default.(bool)
}
