// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/anonymous-author-00000/ra-webs/monitor/ent/evidencelog"
	"github.com/anonymous-author-00000/ra-webs/monitor/ent/ta"
)

// TA is the model entity for the TA schema.
type TA struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// PublicKey holds the value of the "public_key" field.
	PublicKey *[]byte `json:"public_key,omitempty"`
	// IsActive holds the value of the "is_active" field.
	IsActive bool `json:"is_active,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TAQuery when eager-loading is set.
	Edges           TAEdges `json:"edges"`
	evidence_log_ta *int
	selectValues    sql.SelectValues
}

// TAEdges holds the relations/edges for other nodes in the graph.
type TAEdges struct {
	// CtLog holds the value of the ct_log edge.
	CtLog []*CTLog `json:"ct_log,omitempty"`
	// EvidenceLog holds the value of the evidence_log edge.
	EvidenceLog *EvidenceLog `json:"evidence_log,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// CtLogOrErr returns the CtLog value or an error if the edge
// was not loaded in eager-loading.
func (e TAEdges) CtLogOrErr() ([]*CTLog, error) {
	if e.loadedTypes[0] {
		return e.CtLog, nil
	}
	return nil, &NotLoadedError{edge: "ct_log"}
}

// EvidenceLogOrErr returns the EvidenceLog value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TAEdges) EvidenceLogOrErr() (*EvidenceLog, error) {
	if e.EvidenceLog != nil {
		return e.EvidenceLog, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: evidencelog.Label}
	}
	return nil, &NotLoadedError{edge: "evidence_log"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TA) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case ta.FieldPublicKey:
			values[i] = new([]byte)
		case ta.FieldIsActive:
			values[i] = new(sql.NullBool)
		case ta.FieldID:
			values[i] = new(sql.NullInt64)
		case ta.ForeignKeys[0]: // evidence_log_ta
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TA fields.
func (t *TA) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case ta.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			t.ID = int(value.Int64)
		case ta.FieldPublicKey:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field public_key", values[i])
			} else if value != nil {
				t.PublicKey = value
			}
		case ta.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_active", values[i])
			} else if value.Valid {
				t.IsActive = value.Bool
			}
		case ta.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field evidence_log_ta", value)
			} else if value.Valid {
				t.evidence_log_ta = new(int)
				*t.evidence_log_ta = int(value.Int64)
			}
		default:
			t.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TA.
// This includes values selected through modifiers, order, etc.
func (t *TA) Value(name string) (ent.Value, error) {
	return t.selectValues.Get(name)
}

// QueryCtLog queries the "ct_log" edge of the TA entity.
func (t *TA) QueryCtLog() *CTLogQuery {
	return NewTAClient(t.config).QueryCtLog(t)
}

// QueryEvidenceLog queries the "evidence_log" edge of the TA entity.
func (t *TA) QueryEvidenceLog() *EvidenceLogQuery {
	return NewTAClient(t.config).QueryEvidenceLog(t)
}

// Update returns a builder for updating this TA.
// Note that you need to call TA.Unwrap() before calling this method if this TA
// was returned from a transaction, and the transaction was committed or rolled back.
func (t *TA) Update() *TAUpdateOne {
	return NewTAClient(t.config).UpdateOne(t)
}

// Unwrap unwraps the TA entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (t *TA) Unwrap() *TA {
	_tx, ok := t.config.driver.(*txDriver)
	if !ok {
		panic("ent: TA is not a transactional entity")
	}
	t.config.driver = _tx.drv
	return t
}

// String implements the fmt.Stringer.
func (t *TA) String() string {
	var builder strings.Builder
	builder.WriteString("TA(")
	builder.WriteString(fmt.Sprintf("id=%v, ", t.ID))
	if v := t.PublicKey; v != nil {
		builder.WriteString("public_key=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("is_active=")
	builder.WriteString(fmt.Sprintf("%v", t.IsActive))
	builder.WriteByte(')')
	return builder.String()
}

// TAs is a parsable slice of TA.
type TAs []*TA
