// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/anonymous-author-00000/ra-webs/monitor/ent/ctlog"
	"github.com/anonymous-author-00000/ra-webs/monitor/ent/evidencelog"
	"github.com/anonymous-author-00000/ra-webs/monitor/ent/predicate"
	"github.com/anonymous-author-00000/ra-webs/monitor/ent/ta"
)

// TAUpdate is the builder for updating TA entities.
type TAUpdate struct {
	config
	hooks    []Hook
	mutation *TAMutation
}

// Where appends a list predicates to the TAUpdate builder.
func (tu *TAUpdate) Where(ps ...predicate.TA) *TAUpdate {
	tu.mutation.Where(ps...)
	return tu
}

// SetPublicKey sets the "public_key" field.
func (tu *TAUpdate) SetPublicKey(b []byte) *TAUpdate {
	tu.mutation.SetPublicKey(b)
	return tu
}

// SetIsActive sets the "is_active" field.
func (tu *TAUpdate) SetIsActive(b bool) *TAUpdate {
	tu.mutation.SetIsActive(b)
	return tu
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (tu *TAUpdate) SetNillableIsActive(b *bool) *TAUpdate {
	if b != nil {
		tu.SetIsActive(*b)
	}
	return tu
}

// AddCtLogIDs adds the "ct_log" edge to the CTLog entity by IDs.
func (tu *TAUpdate) AddCtLogIDs(ids ...int) *TAUpdate {
	tu.mutation.AddCtLogIDs(ids...)
	return tu
}

// AddCtLog adds the "ct_log" edges to the CTLog entity.
func (tu *TAUpdate) AddCtLog(c ...*CTLog) *TAUpdate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return tu.AddCtLogIDs(ids...)
}

// SetEvidenceLogID sets the "evidence_log" edge to the EvidenceLog entity by ID.
func (tu *TAUpdate) SetEvidenceLogID(id int) *TAUpdate {
	tu.mutation.SetEvidenceLogID(id)
	return tu
}

// SetNillableEvidenceLogID sets the "evidence_log" edge to the EvidenceLog entity by ID if the given value is not nil.
func (tu *TAUpdate) SetNillableEvidenceLogID(id *int) *TAUpdate {
	if id != nil {
		tu = tu.SetEvidenceLogID(*id)
	}
	return tu
}

// SetEvidenceLog sets the "evidence_log" edge to the EvidenceLog entity.
func (tu *TAUpdate) SetEvidenceLog(e *EvidenceLog) *TAUpdate {
	return tu.SetEvidenceLogID(e.ID)
}

// Mutation returns the TAMutation object of the builder.
func (tu *TAUpdate) Mutation() *TAMutation {
	return tu.mutation
}

// ClearCtLog clears all "ct_log" edges to the CTLog entity.
func (tu *TAUpdate) ClearCtLog() *TAUpdate {
	tu.mutation.ClearCtLog()
	return tu
}

// RemoveCtLogIDs removes the "ct_log" edge to CTLog entities by IDs.
func (tu *TAUpdate) RemoveCtLogIDs(ids ...int) *TAUpdate {
	tu.mutation.RemoveCtLogIDs(ids...)
	return tu
}

// RemoveCtLog removes "ct_log" edges to CTLog entities.
func (tu *TAUpdate) RemoveCtLog(c ...*CTLog) *TAUpdate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return tu.RemoveCtLogIDs(ids...)
}

// ClearEvidenceLog clears the "evidence_log" edge to the EvidenceLog entity.
func (tu *TAUpdate) ClearEvidenceLog() *TAUpdate {
	tu.mutation.ClearEvidenceLog()
	return tu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tu *TAUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, tu.sqlSave, tu.mutation, tu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tu *TAUpdate) SaveX(ctx context.Context) int {
	affected, err := tu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tu *TAUpdate) Exec(ctx context.Context) error {
	_, err := tu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tu *TAUpdate) ExecX(ctx context.Context) {
	if err := tu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (tu *TAUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(ta.Table, ta.Columns, sqlgraph.NewFieldSpec(ta.FieldID, field.TypeInt))
	if ps := tu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tu.mutation.PublicKey(); ok {
		_spec.SetField(ta.FieldPublicKey, field.TypeBytes, value)
	}
	if value, ok := tu.mutation.IsActive(); ok {
		_spec.SetField(ta.FieldIsActive, field.TypeBool, value)
	}
	if tu.mutation.CtLogCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   ta.CtLogTable,
			Columns: []string{ta.CtLogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ctlog.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.RemovedCtLogIDs(); len(nodes) > 0 && !tu.mutation.CtLogCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   ta.CtLogTable,
			Columns: []string{ta.CtLogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ctlog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.CtLogIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   ta.CtLogTable,
			Columns: []string{ta.CtLogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ctlog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tu.mutation.EvidenceLogCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   ta.EvidenceLogTable,
			Columns: []string{ta.EvidenceLogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evidencelog.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.EvidenceLogIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   ta.EvidenceLogTable,
			Columns: []string{ta.EvidenceLogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evidencelog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, tu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ta.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	tu.mutation.done = true
	return n, nil
}

// TAUpdateOne is the builder for updating a single TA entity.
type TAUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TAMutation
}

// SetPublicKey sets the "public_key" field.
func (tuo *TAUpdateOne) SetPublicKey(b []byte) *TAUpdateOne {
	tuo.mutation.SetPublicKey(b)
	return tuo
}

// SetIsActive sets the "is_active" field.
func (tuo *TAUpdateOne) SetIsActive(b bool) *TAUpdateOne {
	tuo.mutation.SetIsActive(b)
	return tuo
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (tuo *TAUpdateOne) SetNillableIsActive(b *bool) *TAUpdateOne {
	if b != nil {
		tuo.SetIsActive(*b)
	}
	return tuo
}

// AddCtLogIDs adds the "ct_log" edge to the CTLog entity by IDs.
func (tuo *TAUpdateOne) AddCtLogIDs(ids ...int) *TAUpdateOne {
	tuo.mutation.AddCtLogIDs(ids...)
	return tuo
}

// AddCtLog adds the "ct_log" edges to the CTLog entity.
func (tuo *TAUpdateOne) AddCtLog(c ...*CTLog) *TAUpdateOne {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return tuo.AddCtLogIDs(ids...)
}

// SetEvidenceLogID sets the "evidence_log" edge to the EvidenceLog entity by ID.
func (tuo *TAUpdateOne) SetEvidenceLogID(id int) *TAUpdateOne {
	tuo.mutation.SetEvidenceLogID(id)
	return tuo
}

// SetNillableEvidenceLogID sets the "evidence_log" edge to the EvidenceLog entity by ID if the given value is not nil.
func (tuo *TAUpdateOne) SetNillableEvidenceLogID(id *int) *TAUpdateOne {
	if id != nil {
		tuo = tuo.SetEvidenceLogID(*id)
	}
	return tuo
}

// SetEvidenceLog sets the "evidence_log" edge to the EvidenceLog entity.
func (tuo *TAUpdateOne) SetEvidenceLog(e *EvidenceLog) *TAUpdateOne {
	return tuo.SetEvidenceLogID(e.ID)
}

// Mutation returns the TAMutation object of the builder.
func (tuo *TAUpdateOne) Mutation() *TAMutation {
	return tuo.mutation
}

// ClearCtLog clears all "ct_log" edges to the CTLog entity.
func (tuo *TAUpdateOne) ClearCtLog() *TAUpdateOne {
	tuo.mutation.ClearCtLog()
	return tuo
}

// RemoveCtLogIDs removes the "ct_log" edge to CTLog entities by IDs.
func (tuo *TAUpdateOne) RemoveCtLogIDs(ids ...int) *TAUpdateOne {
	tuo.mutation.RemoveCtLogIDs(ids...)
	return tuo
}

// RemoveCtLog removes "ct_log" edges to CTLog entities.
func (tuo *TAUpdateOne) RemoveCtLog(c ...*CTLog) *TAUpdateOne {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return tuo.RemoveCtLogIDs(ids...)
}

// ClearEvidenceLog clears the "evidence_log" edge to the EvidenceLog entity.
func (tuo *TAUpdateOne) ClearEvidenceLog() *TAUpdateOne {
	tuo.mutation.ClearEvidenceLog()
	return tuo
}

// Where appends a list predicates to the TAUpdate builder.
func (tuo *TAUpdateOne) Where(ps ...predicate.TA) *TAUpdateOne {
	tuo.mutation.Where(ps...)
	return tuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tuo *TAUpdateOne) Select(field string, fields ...string) *TAUpdateOne {
	tuo.fields = append([]string{field}, fields...)
	return tuo
}

// Save executes the query and returns the updated TA entity.
func (tuo *TAUpdateOne) Save(ctx context.Context) (*TA, error) {
	return withHooks(ctx, tuo.sqlSave, tuo.mutation, tuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tuo *TAUpdateOne) SaveX(ctx context.Context) *TA {
	node, err := tuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tuo *TAUpdateOne) Exec(ctx context.Context) error {
	_, err := tuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tuo *TAUpdateOne) ExecX(ctx context.Context) {
	if err := tuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (tuo *TAUpdateOne) sqlSave(ctx context.Context) (_node *TA, err error) {
	_spec := sqlgraph.NewUpdateSpec(ta.Table, ta.Columns, sqlgraph.NewFieldSpec(ta.FieldID, field.TypeInt))
	id, ok := tuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TA.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ta.FieldID)
		for _, f := range fields {
			if !ta.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != ta.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tuo.mutation.PublicKey(); ok {
		_spec.SetField(ta.FieldPublicKey, field.TypeBytes, value)
	}
	if value, ok := tuo.mutation.IsActive(); ok {
		_spec.SetField(ta.FieldIsActive, field.TypeBool, value)
	}
	if tuo.mutation.CtLogCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   ta.CtLogTable,
			Columns: []string{ta.CtLogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ctlog.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.RemovedCtLogIDs(); len(nodes) > 0 && !tuo.mutation.CtLogCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   ta.CtLogTable,
			Columns: []string{ta.CtLogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ctlog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.CtLogIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   ta.CtLogTable,
			Columns: []string{ta.CtLogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ctlog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tuo.mutation.EvidenceLogCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   ta.EvidenceLogTable,
			Columns: []string{ta.EvidenceLogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evidencelog.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.EvidenceLogIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   ta.EvidenceLogTable,
			Columns: []string{ta.EvidenceLogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evidencelog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TA{config: tuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ta.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	tuo.mutation.done = true
	return _node, nil
}
