// Code generated by ent, DO NOT EDIT.

package evidencelog

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/anonymous-author-00000/ra-webs/monitor/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.EvidenceLog {
	return predicate.EvidenceLog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.EvidenceLog {
	return predicate.EvidenceLog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.EvidenceLog {
	return predicate.EvidenceLog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.EvidenceLog {
	return predicate.EvidenceLog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.EvidenceLog {
	return predicate.EvidenceLog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.EvidenceLog {
	return predicate.EvidenceLog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.EvidenceLog {
	return predicate.EvidenceLog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.EvidenceLog {
	return predicate.EvidenceLog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.EvidenceLog {
	return predicate.EvidenceLog(sql.FieldLTE(FieldID, id))
}

// Evidence applies equality check predicate on the "evidence" field. It's identical to EvidenceEQ.
func Evidence(v string) predicate.EvidenceLog {
	return predicate.EvidenceLog(sql.FieldEQ(FieldEvidence, v))
}

// Repository applies equality check predicate on the "repository" field. It's identical to RepositoryEQ.
func Repository(v string) predicate.EvidenceLog {
	return predicate.EvidenceLog(sql.FieldEQ(FieldRepository, v))
}

// CommitID applies equality check predicate on the "commit_id" field. It's identical to CommitIDEQ.
func CommitID(v string) predicate.EvidenceLog {
	return predicate.EvidenceLog(sql.FieldEQ(FieldCommitID, v))
}

// UniqueID applies equality check predicate on the "unique_id" field. It's identical to UniqueIDEQ.
func UniqueID(v []byte) predicate.EvidenceLog {
	return predicate.EvidenceLog(sql.FieldEQ(FieldUniqueID, v))
}

// EvidenceEQ applies the EQ predicate on the "evidence" field.
func EvidenceEQ(v string) predicate.EvidenceLog {
	return predicate.EvidenceLog(sql.FieldEQ(FieldEvidence, v))
}

// EvidenceNEQ applies the NEQ predicate on the "evidence" field.
func EvidenceNEQ(v string) predicate.EvidenceLog {
	return predicate.EvidenceLog(sql.FieldNEQ(FieldEvidence, v))
}

// EvidenceIn applies the In predicate on the "evidence" field.
func EvidenceIn(vs ...string) predicate.EvidenceLog {
	return predicate.EvidenceLog(sql.FieldIn(FieldEvidence, vs...))
}

// EvidenceNotIn applies the NotIn predicate on the "evidence" field.
func EvidenceNotIn(vs ...string) predicate.EvidenceLog {
	return predicate.EvidenceLog(sql.FieldNotIn(FieldEvidence, vs...))
}

// EvidenceGT applies the GT predicate on the "evidence" field.
func EvidenceGT(v string) predicate.EvidenceLog {
	return predicate.EvidenceLog(sql.FieldGT(FieldEvidence, v))
}

// EvidenceGTE applies the GTE predicate on the "evidence" field.
func EvidenceGTE(v string) predicate.EvidenceLog {
	return predicate.EvidenceLog(sql.FieldGTE(FieldEvidence, v))
}

// EvidenceLT applies the LT predicate on the "evidence" field.
func EvidenceLT(v string) predicate.EvidenceLog {
	return predicate.EvidenceLog(sql.FieldLT(FieldEvidence, v))
}

// EvidenceLTE applies the LTE predicate on the "evidence" field.
func EvidenceLTE(v string) predicate.EvidenceLog {
	return predicate.EvidenceLog(sql.FieldLTE(FieldEvidence, v))
}

// EvidenceContains applies the Contains predicate on the "evidence" field.
func EvidenceContains(v string) predicate.EvidenceLog {
	return predicate.EvidenceLog(sql.FieldContains(FieldEvidence, v))
}

// EvidenceHasPrefix applies the HasPrefix predicate on the "evidence" field.
func EvidenceHasPrefix(v string) predicate.EvidenceLog {
	return predicate.EvidenceLog(sql.FieldHasPrefix(FieldEvidence, v))
}

// EvidenceHasSuffix applies the HasSuffix predicate on the "evidence" field.
func EvidenceHasSuffix(v string) predicate.EvidenceLog {
	return predicate.EvidenceLog(sql.FieldHasSuffix(FieldEvidence, v))
}

// EvidenceEqualFold applies the EqualFold predicate on the "evidence" field.
func EvidenceEqualFold(v string) predicate.EvidenceLog {
	return predicate.EvidenceLog(sql.FieldEqualFold(FieldEvidence, v))
}

// EvidenceContainsFold applies the ContainsFold predicate on the "evidence" field.
func EvidenceContainsFold(v string) predicate.EvidenceLog {
	return predicate.EvidenceLog(sql.FieldContainsFold(FieldEvidence, v))
}

// RepositoryEQ applies the EQ predicate on the "repository" field.
func RepositoryEQ(v string) predicate.EvidenceLog {
	return predicate.EvidenceLog(sql.FieldEQ(FieldRepository, v))
}

// RepositoryNEQ applies the NEQ predicate on the "repository" field.
func RepositoryNEQ(v string) predicate.EvidenceLog {
	return predicate.EvidenceLog(sql.FieldNEQ(FieldRepository, v))
}

// RepositoryIn applies the In predicate on the "repository" field.
func RepositoryIn(vs ...string) predicate.EvidenceLog {
	return predicate.EvidenceLog(sql.FieldIn(FieldRepository, vs...))
}

// RepositoryNotIn applies the NotIn predicate on the "repository" field.
func RepositoryNotIn(vs ...string) predicate.EvidenceLog {
	return predicate.EvidenceLog(sql.FieldNotIn(FieldRepository, vs...))
}

// RepositoryGT applies the GT predicate on the "repository" field.
func RepositoryGT(v string) predicate.EvidenceLog {
	return predicate.EvidenceLog(sql.FieldGT(FieldRepository, v))
}

// RepositoryGTE applies the GTE predicate on the "repository" field.
func RepositoryGTE(v string) predicate.EvidenceLog {
	return predicate.EvidenceLog(sql.FieldGTE(FieldRepository, v))
}

// RepositoryLT applies the LT predicate on the "repository" field.
func RepositoryLT(v string) predicate.EvidenceLog {
	return predicate.EvidenceLog(sql.FieldLT(FieldRepository, v))
}

// RepositoryLTE applies the LTE predicate on the "repository" field.
func RepositoryLTE(v string) predicate.EvidenceLog {
	return predicate.EvidenceLog(sql.FieldLTE(FieldRepository, v))
}

// RepositoryContains applies the Contains predicate on the "repository" field.
func RepositoryContains(v string) predicate.EvidenceLog {
	return predicate.EvidenceLog(sql.FieldContains(FieldRepository, v))
}

// RepositoryHasPrefix applies the HasPrefix predicate on the "repository" field.
func RepositoryHasPrefix(v string) predicate.EvidenceLog {
	return predicate.EvidenceLog(sql.FieldHasPrefix(FieldRepository, v))
}

// RepositoryHasSuffix applies the HasSuffix predicate on the "repository" field.
func RepositoryHasSuffix(v string) predicate.EvidenceLog {
	return predicate.EvidenceLog(sql.FieldHasSuffix(FieldRepository, v))
}

// RepositoryEqualFold applies the EqualFold predicate on the "repository" field.
func RepositoryEqualFold(v string) predicate.EvidenceLog {
	return predicate.EvidenceLog(sql.FieldEqualFold(FieldRepository, v))
}

// RepositoryContainsFold applies the ContainsFold predicate on the "repository" field.
func RepositoryContainsFold(v string) predicate.EvidenceLog {
	return predicate.EvidenceLog(sql.FieldContainsFold(FieldRepository, v))
}

// CommitIDEQ applies the EQ predicate on the "commit_id" field.
func CommitIDEQ(v string) predicate.EvidenceLog {
	return predicate.EvidenceLog(sql.FieldEQ(FieldCommitID, v))
}

// CommitIDNEQ applies the NEQ predicate on the "commit_id" field.
func CommitIDNEQ(v string) predicate.EvidenceLog {
	return predicate.EvidenceLog(sql.FieldNEQ(FieldCommitID, v))
}

// CommitIDIn applies the In predicate on the "commit_id" field.
func CommitIDIn(vs ...string) predicate.EvidenceLog {
	return predicate.EvidenceLog(sql.FieldIn(FieldCommitID, vs...))
}

// CommitIDNotIn applies the NotIn predicate on the "commit_id" field.
func CommitIDNotIn(vs ...string) predicate.EvidenceLog {
	return predicate.EvidenceLog(sql.FieldNotIn(FieldCommitID, vs...))
}

// CommitIDGT applies the GT predicate on the "commit_id" field.
func CommitIDGT(v string) predicate.EvidenceLog {
	return predicate.EvidenceLog(sql.FieldGT(FieldCommitID, v))
}

// CommitIDGTE applies the GTE predicate on the "commit_id" field.
func CommitIDGTE(v string) predicate.EvidenceLog {
	return predicate.EvidenceLog(sql.FieldGTE(FieldCommitID, v))
}

// CommitIDLT applies the LT predicate on the "commit_id" field.
func CommitIDLT(v string) predicate.EvidenceLog {
	return predicate.EvidenceLog(sql.FieldLT(FieldCommitID, v))
}

// CommitIDLTE applies the LTE predicate on the "commit_id" field.
func CommitIDLTE(v string) predicate.EvidenceLog {
	return predicate.EvidenceLog(sql.FieldLTE(FieldCommitID, v))
}

// CommitIDContains applies the Contains predicate on the "commit_id" field.
func CommitIDContains(v string) predicate.EvidenceLog {
	return predicate.EvidenceLog(sql.FieldContains(FieldCommitID, v))
}

// CommitIDHasPrefix applies the HasPrefix predicate on the "commit_id" field.
func CommitIDHasPrefix(v string) predicate.EvidenceLog {
	return predicate.EvidenceLog(sql.FieldHasPrefix(FieldCommitID, v))
}

// CommitIDHasSuffix applies the HasSuffix predicate on the "commit_id" field.
func CommitIDHasSuffix(v string) predicate.EvidenceLog {
	return predicate.EvidenceLog(sql.FieldHasSuffix(FieldCommitID, v))
}

// CommitIDEqualFold applies the EqualFold predicate on the "commit_id" field.
func CommitIDEqualFold(v string) predicate.EvidenceLog {
	return predicate.EvidenceLog(sql.FieldEqualFold(FieldCommitID, v))
}

// CommitIDContainsFold applies the ContainsFold predicate on the "commit_id" field.
func CommitIDContainsFold(v string) predicate.EvidenceLog {
	return predicate.EvidenceLog(sql.FieldContainsFold(FieldCommitID, v))
}

// UniqueIDEQ applies the EQ predicate on the "unique_id" field.
func UniqueIDEQ(v []byte) predicate.EvidenceLog {
	return predicate.EvidenceLog(sql.FieldEQ(FieldUniqueID, v))
}

// UniqueIDNEQ applies the NEQ predicate on the "unique_id" field.
func UniqueIDNEQ(v []byte) predicate.EvidenceLog {
	return predicate.EvidenceLog(sql.FieldNEQ(FieldUniqueID, v))
}

// UniqueIDIn applies the In predicate on the "unique_id" field.
func UniqueIDIn(vs ...[]byte) predicate.EvidenceLog {
	return predicate.EvidenceLog(sql.FieldIn(FieldUniqueID, vs...))
}

// UniqueIDNotIn applies the NotIn predicate on the "unique_id" field.
func UniqueIDNotIn(vs ...[]byte) predicate.EvidenceLog {
	return predicate.EvidenceLog(sql.FieldNotIn(FieldUniqueID, vs...))
}

// UniqueIDGT applies the GT predicate on the "unique_id" field.
func UniqueIDGT(v []byte) predicate.EvidenceLog {
	return predicate.EvidenceLog(sql.FieldGT(FieldUniqueID, v))
}

// UniqueIDGTE applies the GTE predicate on the "unique_id" field.
func UniqueIDGTE(v []byte) predicate.EvidenceLog {
	return predicate.EvidenceLog(sql.FieldGTE(FieldUniqueID, v))
}

// UniqueIDLT applies the LT predicate on the "unique_id" field.
func UniqueIDLT(v []byte) predicate.EvidenceLog {
	return predicate.EvidenceLog(sql.FieldLT(FieldUniqueID, v))
}

// UniqueIDLTE applies the LTE predicate on the "unique_id" field.
func UniqueIDLTE(v []byte) predicate.EvidenceLog {
	return predicate.EvidenceLog(sql.FieldLTE(FieldUniqueID, v))
}

// HasTa applies the HasEdge predicate on the "ta" edge.
func HasTa() predicate.EvidenceLog {
	return predicate.EvidenceLog(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, TaTable, TaColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTaWith applies the HasEdge predicate on the "ta" edge with a given conditions (other predicates).
func HasTaWith(preds ...predicate.TA) predicate.EvidenceLog {
	return predicate.EvidenceLog(func(s *sql.Selector) {
		step := newTaStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.EvidenceLog) predicate.EvidenceLog {
	return predicate.EvidenceLog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.EvidenceLog) predicate.EvidenceLog {
	return predicate.EvidenceLog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.EvidenceLog) predicate.EvidenceLog {
	return predicate.EvidenceLog(sql.NotPredicates(p))
}
