// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/anonymous-author-00000/ra-webs/devkit/service/ent/predicate"
	"github.com/anonymous-author-00000/ra-webs/devkit/service/ent/ta"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeTA = "TA"
)

// TAMutation represents an operation that mutates the TA nodes in the graph.
type TAMutation struct {
	config
	op            Op
	typ           string
	id            *int
	evidence      *string
	repository    *string
	commit_id     *string
	public_key    *[]byte
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*TA, error)
	predicates    []predicate.TA
}

var _ ent.Mutation = (*TAMutation)(nil)

// taOption allows management of the mutation configuration using functional options.
type taOption func(*TAMutation)

// newTAMutation creates new mutation for the TA entity.
func newTAMutation(c config, op Op, opts ...taOption) *TAMutation {
	m := &TAMutation{
		config:        c,
		op:            op,
		typ:           TypeTA,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withTAID sets the ID field of the mutation.
func withTAID(id int) taOption {
	return func(m *TAMutation) {
		var (
			err   error
			once  sync.Once
			value *TA
		)
		m.oldValue = func(ctx context.Context) (*TA, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().TA.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withTA sets the old TA of the mutation.
func withTA(node *TA) taOption {
	return func(m *TAMutation) {
		m.oldValue = func(context.Context) (*TA, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m TAMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m TAMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *TAMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *TAMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().TA.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetEvidence sets the "evidence" field.
func (m *TAMutation) SetEvidence(s string) {
	m.evidence = &s
}

// Evidence returns the value of the "evidence" field in the mutation.
func (m *TAMutation) Evidence() (r string, exists bool) {
	v := m.evidence
	if v == nil {
		return
	}
	return *v, true
}

// OldEvidence returns the old "evidence" field's value of the TA entity.
// If the TA object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TAMutation) OldEvidence(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldEvidence is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldEvidence requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldEvidence: %w", err)
	}
	return oldValue.Evidence, nil
}

// ResetEvidence resets all changes to the "evidence" field.
func (m *TAMutation) ResetEvidence() {
	m.evidence = nil
}

// SetRepository sets the "repository" field.
func (m *TAMutation) SetRepository(s string) {
	m.repository = &s
}

// Repository returns the value of the "repository" field in the mutation.
func (m *TAMutation) Repository() (r string, exists bool) {
	v := m.repository
	if v == nil {
		return
	}
	return *v, true
}

// OldRepository returns the old "repository" field's value of the TA entity.
// If the TA object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TAMutation) OldRepository(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRepository is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRepository requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRepository: %w", err)
	}
	return oldValue.Repository, nil
}

// ResetRepository resets all changes to the "repository" field.
func (m *TAMutation) ResetRepository() {
	m.repository = nil
}

// SetCommitID sets the "commit_id" field.
func (m *TAMutation) SetCommitID(s string) {
	m.commit_id = &s
}

// CommitID returns the value of the "commit_id" field in the mutation.
func (m *TAMutation) CommitID() (r string, exists bool) {
	v := m.commit_id
	if v == nil {
		return
	}
	return *v, true
}

// OldCommitID returns the old "commit_id" field's value of the TA entity.
// If the TA object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TAMutation) OldCommitID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCommitID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCommitID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCommitID: %w", err)
	}
	return oldValue.CommitID, nil
}

// ResetCommitID resets all changes to the "commit_id" field.
func (m *TAMutation) ResetCommitID() {
	m.commit_id = nil
}

// SetPublicKey sets the "public_key" field.
func (m *TAMutation) SetPublicKey(b []byte) {
	m.public_key = &b
}

// PublicKey returns the value of the "public_key" field in the mutation.
func (m *TAMutation) PublicKey() (r []byte, exists bool) {
	v := m.public_key
	if v == nil {
		return
	}
	return *v, true
}

// OldPublicKey returns the old "public_key" field's value of the TA entity.
// If the TA object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TAMutation) OldPublicKey(ctx context.Context) (v []byte, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPublicKey is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPublicKey requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPublicKey: %w", err)
	}
	return oldValue.PublicKey, nil
}

// ResetPublicKey resets all changes to the "public_key" field.
func (m *TAMutation) ResetPublicKey() {
	m.public_key = nil
}

// Where appends a list predicates to the TAMutation builder.
func (m *TAMutation) Where(ps ...predicate.TA) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the TAMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *TAMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.TA, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *TAMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *TAMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (TA).
func (m *TAMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *TAMutation) Fields() []string {
	fields := make([]string, 0, 4)
	if m.evidence != nil {
		fields = append(fields, ta.FieldEvidence)
	}
	if m.repository != nil {
		fields = append(fields, ta.FieldRepository)
	}
	if m.commit_id != nil {
		fields = append(fields, ta.FieldCommitID)
	}
	if m.public_key != nil {
		fields = append(fields, ta.FieldPublicKey)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *TAMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case ta.FieldEvidence:
		return m.Evidence()
	case ta.FieldRepository:
		return m.Repository()
	case ta.FieldCommitID:
		return m.CommitID()
	case ta.FieldPublicKey:
		return m.PublicKey()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *TAMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case ta.FieldEvidence:
		return m.OldEvidence(ctx)
	case ta.FieldRepository:
		return m.OldRepository(ctx)
	case ta.FieldCommitID:
		return m.OldCommitID(ctx)
	case ta.FieldPublicKey:
		return m.OldPublicKey(ctx)
	}
	return nil, fmt.Errorf("unknown TA field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *TAMutation) SetField(name string, value ent.Value) error {
	switch name {
	case ta.FieldEvidence:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetEvidence(v)
		return nil
	case ta.FieldRepository:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRepository(v)
		return nil
	case ta.FieldCommitID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCommitID(v)
		return nil
	case ta.FieldPublicKey:
		v, ok := value.([]byte)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPublicKey(v)
		return nil
	}
	return fmt.Errorf("unknown TA field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *TAMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *TAMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *TAMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown TA numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *TAMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *TAMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *TAMutation) ClearField(name string) error {
	return fmt.Errorf("unknown TA nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *TAMutation) ResetField(name string) error {
	switch name {
	case ta.FieldEvidence:
		m.ResetEvidence()
		return nil
	case ta.FieldRepository:
		m.ResetRepository()
		return nil
	case ta.FieldCommitID:
		m.ResetCommitID()
		return nil
	case ta.FieldPublicKey:
		m.ResetPublicKey()
		return nil
	}
	return fmt.Errorf("unknown TA field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *TAMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *TAMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *TAMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *TAMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *TAMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *TAMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *TAMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown TA unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *TAMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown TA edge %s", name)
}
