// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/anonymous-author-00000/ra-webs/devkit/service/ent/ta"
)

// TACreate is the builder for creating a TA entity.
type TACreate struct {
	config
	mutation *TAMutation
	hooks    []Hook
}

// SetEvidence sets the "evidence" field.
func (tc *TACreate) SetEvidence(s string) *TACreate {
	tc.mutation.SetEvidence(s)
	return tc
}

// SetRepository sets the "repository" field.
func (tc *TACreate) SetRepository(s string) *TACreate {
	tc.mutation.SetRepository(s)
	return tc
}

// SetCommitID sets the "commit_id" field.
func (tc *TACreate) SetCommitID(s string) *TACreate {
	tc.mutation.SetCommitID(s)
	return tc
}

// SetPublicKey sets the "public_key" field.
func (tc *TACreate) SetPublicKey(b []byte) *TACreate {
	tc.mutation.SetPublicKey(b)
	return tc
}

// Mutation returns the TAMutation object of the builder.
func (tc *TACreate) Mutation() *TAMutation {
	return tc.mutation
}

// Save creates the TA in the database.
func (tc *TACreate) Save(ctx context.Context) (*TA, error) {
	return withHooks(ctx, tc.sqlSave, tc.mutation, tc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (tc *TACreate) SaveX(ctx context.Context) *TA {
	v, err := tc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tc *TACreate) Exec(ctx context.Context) error {
	_, err := tc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tc *TACreate) ExecX(ctx context.Context) {
	if err := tc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tc *TACreate) check() error {
	if _, ok := tc.mutation.Evidence(); !ok {
		return &ValidationError{Name: "evidence", err: errors.New(`ent: missing required field "TA.evidence"`)}
	}
	if _, ok := tc.mutation.Repository(); !ok {
		return &ValidationError{Name: "repository", err: errors.New(`ent: missing required field "TA.repository"`)}
	}
	if _, ok := tc.mutation.CommitID(); !ok {
		return &ValidationError{Name: "commit_id", err: errors.New(`ent: missing required field "TA.commit_id"`)}
	}
	if _, ok := tc.mutation.PublicKey(); !ok {
		return &ValidationError{Name: "public_key", err: errors.New(`ent: missing required field "TA.public_key"`)}
	}
	return nil
}

func (tc *TACreate) sqlSave(ctx context.Context) (*TA, error) {
	if err := tc.check(); err != nil {
		return nil, err
	}
	_node, _spec := tc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	tc.mutation.id = &_node.ID
	tc.mutation.done = true
	return _node, nil
}

func (tc *TACreate) createSpec() (*TA, *sqlgraph.CreateSpec) {
	var (
		_node = &TA{config: tc.config}
		_spec = sqlgraph.NewCreateSpec(ta.Table, sqlgraph.NewFieldSpec(ta.FieldID, field.TypeInt))
	)
	if value, ok := tc.mutation.Evidence(); ok {
		_spec.SetField(ta.FieldEvidence, field.TypeString, value)
		_node.Evidence = value
	}
	if value, ok := tc.mutation.Repository(); ok {
		_spec.SetField(ta.FieldRepository, field.TypeString, value)
		_node.Repository = value
	}
	if value, ok := tc.mutation.CommitID(); ok {
		_spec.SetField(ta.FieldCommitID, field.TypeString, value)
		_node.CommitID = value
	}
	if value, ok := tc.mutation.PublicKey(); ok {
		_spec.SetField(ta.FieldPublicKey, field.TypeBytes, value)
		_node.PublicKey = value
	}
	return _node, _spec
}

// TACreateBulk is the builder for creating many TA entities in bulk.
type TACreateBulk struct {
	config
	err      error
	builders []*TACreate
}

// Save creates the TA entities in the database.
func (tcb *TACreateBulk) Save(ctx context.Context) ([]*TA, error) {
	if tcb.err != nil {
		return nil, tcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(tcb.builders))
	nodes := make([]*TA, len(tcb.builders))
	mutators := make([]Mutator, len(tcb.builders))
	for i := range tcb.builders {
		func(i int, root context.Context) {
			builder := tcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TAMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tcb *TACreateBulk) SaveX(ctx context.Context) []*TA {
	v, err := tcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tcb *TACreateBulk) Exec(ctx context.Context) error {
	_, err := tcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tcb *TACreateBulk) ExecX(ctx context.Context) {
	if err := tcb.Exec(ctx); err != nil {
		panic(err)
	}
}
