// Code generated by ent, DO NOT EDIT.

package ctlog

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/anonymous-author-00000/ra-webs/monitor/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.CTLog {
	return predicate.CTLog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.CTLog {
	return predicate.CTLog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.CTLog {
	return predicate.CTLog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.CTLog {
	return predicate.CTLog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.CTLog {
	return predicate.CTLog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.CTLog {
	return predicate.CTLog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.CTLog {
	return predicate.CTLog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.CTLog {
	return predicate.CTLog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.CTLog {
	return predicate.CTLog(sql.FieldLTE(FieldID, id))
}

// MonitorLogID applies equality check predicate on the "monitor_log_id" field. It's identical to MonitorLogIDEQ.
func MonitorLogID(v int) predicate.CTLog {
	return predicate.CTLog(sql.FieldEQ(FieldMonitorLogID, v))
}

// MonitorLogIDEQ applies the EQ predicate on the "monitor_log_id" field.
func MonitorLogIDEQ(v int) predicate.CTLog {
	return predicate.CTLog(sql.FieldEQ(FieldMonitorLogID, v))
}

// MonitorLogIDNEQ applies the NEQ predicate on the "monitor_log_id" field.
func MonitorLogIDNEQ(v int) predicate.CTLog {
	return predicate.CTLog(sql.FieldNEQ(FieldMonitorLogID, v))
}

// MonitorLogIDIn applies the In predicate on the "monitor_log_id" field.
func MonitorLogIDIn(vs ...int) predicate.CTLog {
	return predicate.CTLog(sql.FieldIn(FieldMonitorLogID, vs...))
}

// MonitorLogIDNotIn applies the NotIn predicate on the "monitor_log_id" field.
func MonitorLogIDNotIn(vs ...int) predicate.CTLog {
	return predicate.CTLog(sql.FieldNotIn(FieldMonitorLogID, vs...))
}

// MonitorLogIDGT applies the GT predicate on the "monitor_log_id" field.
func MonitorLogIDGT(v int) predicate.CTLog {
	return predicate.CTLog(sql.FieldGT(FieldMonitorLogID, v))
}

// MonitorLogIDGTE applies the GTE predicate on the "monitor_log_id" field.
func MonitorLogIDGTE(v int) predicate.CTLog {
	return predicate.CTLog(sql.FieldGTE(FieldMonitorLogID, v))
}

// MonitorLogIDLT applies the LT predicate on the "monitor_log_id" field.
func MonitorLogIDLT(v int) predicate.CTLog {
	return predicate.CTLog(sql.FieldLT(FieldMonitorLogID, v))
}

// MonitorLogIDLTE applies the LTE predicate on the "monitor_log_id" field.
func MonitorLogIDLTE(v int) predicate.CTLog {
	return predicate.CTLog(sql.FieldLTE(FieldMonitorLogID, v))
}

// HasTa applies the HasEdge predicate on the "ta" edge.
func HasTa() predicate.CTLog {
	return predicate.CTLog(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, TaTable, TaColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTaWith applies the HasEdge predicate on the "ta" edge with a given conditions (other predicates).
func HasTaWith(preds ...predicate.TA) predicate.CTLog {
	return predicate.CTLog(func(s *sql.Selector) {
		step := newTaStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CTLog) predicate.CTLog {
	return predicate.CTLog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CTLog) predicate.CTLog {
	return predicate.CTLog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CTLog) predicate.CTLog {
	return predicate.CTLog(sql.NotPredicates(p))
}
